### ISSUE TITLE
老大再发个v2版本的小白教程吧

### ISSUE THREAD

**Issue by zkzipoo** [GreatYYX/dnvod-ad-killer#2]
看了v1版本的教程以为差不多，可是我还是不会用，chrome浏览器，windows10，服务启动在wsl

按照步骤一二三配置好了，安装了mitmproxy以及安装了证书

配置了switchyomega为localhost 8899以及host wildcard 规则，pac不知道怎么配置就没有弄

清除了缓存，启动了服务
kai@DESKTOP-CTJD00V:~/github/dnvod-ad-killer$ mitmdump -p 8899 -s call_killer.py
Loading script call_killer.py
Proxy server listening at http://*:8899

只是发现mitmdump没有任何的访问记录，同时多瑙广告也还在，求解

**Comment by GreatYYX** [comment]
@zkzipoo 不好意思啊没写的很详细。
- 关于pac：不是必须的，如果你会手动配置规则的话。如果你不想自己配置规则，switch omega（sw）支持导入pac，可以在sw里选new profile -> pac profile -> pac url指向我这个文件就可以。
![sw1](https://user-images.githubusercontent.com/8329846/51590054-9204d600-1e9d-11e9-8390-4932ccb81ff4.PNG)

- 关于mitmproxy没有收到流量转发：不要配置host wildcard先，把所有流量都导到代理上，看看有没有反应。直接在sw里创建一个new profile，然后protocol是`http`，server是`::1`，port是`8899`。然后应用这个profile（所有浏览全部靠这个转发），如果没有收到流量则可能是你chrome代理有cache（其他插件），chrome://net-internals/#proxy 可以看一下这儿。如果正常了，再在autoswitch中配置规则，然后切换到autoswitch。

我在win10上试了下，应该是可以的。如果有问题再留言。

**Comment by GreatYYX** [comment]
btw，我不知道你是不是subsystem的关系，我在windows上测试时候我是直接装到主系统的。你可能需要建立subsystem和主os的端口映射：https://www.nextofwindows.com/allow-server-running-inside-wsl-to-be-accessible-outside-windows-10-host

**Comment by zkzipoo** [comment]
老大，感谢更新，我测试了一下，最终发现我的问题是出在omegaswitchy上面，现在从新下载安装后解决了。解决思路是首先使用windows10 自带的proxy，配置后mitm.it可以正常显示同时mitmproxy有流量，但是转用omegaswitchy后无效了。不过现在chrome://net-internals/#proxy这个里面还是空的，不知道为啥~ anyway，谢谢啦
